#!/bin/bash

set -e

# This should be configured properly
AGDA_BIN=agda
SOURCE_DIR=_sources
TARGET_DIR="$(pwd)"
STD_LIB="$(cd ../../std-lib/src; pwd)"

cd "$SOURCE_DIR"
find . -not \( -path "./_*" \) -name '*.rst' | while read a; do
    if [[ "$a" == *.lagda.rst ]]; then
        $AGDA_BIN --verbose=0 -i"$STD_LIB" -i. "$a"
    fi
    target="$TARGET_DIR/$a"
    mkdir -p "$(dirname "$target")"
    cp "$a" "$target"
done
    
